// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID          string  `json:"id"`
	Terminology *string `json:"terminology"`
	Definition  *string `json:"definition"`
	CourseID    string  `json:"courseId"`
}

type CardInput struct {
	ID          string  `json:"id"`
	Terminology *string `json:"terminology"`
	Definition  *string `json:"definition"`
}

type Course struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CourseInput struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type GetCardsInput struct {
	CourseID   *string          `json:"courseID"`
	Pagination *PaginationInput `json:"pagination"`
}

type GetCardsResponse struct {
	Data     []*Card   `json:"data"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type NewCardInput struct {
	CourseID    string  `json:"courseId"`
	Terminology *string `json:"terminology"`
	Definition  *string `json:"definition"`
}

type NewCardInputFromText struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Text        string  `json:"text"`
}

type NewCourseInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewUser struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Notification struct {
	ID             string  `json:"id"`
	UserID         string  `json:"userID"`
	CourseID       *string `json:"courseID"`
	Sub            *string `json:"sub"`
	SubscribeState *bool   `json:"subscribeState"`
	EveryMinute    *int    `json:"everyMinute"`
}

type PageInfo struct {
	Cursor      string `json:"cursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}

type PaginationInput struct {
	Cursor *string `json:"cursor"`
	Limit  int     `json:"limit"`
}

// `Time` is a simple type only containing the current time as
// a unix epoch timestamp and a string timestamp.
type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type NotificationRequest struct {
	CourseID       *string `json:"courseID"`
	Sub            *string `json:"sub"`
	SubscribeState *bool   `json:"subscribeState"`
	EveryMinute    *int    `json:"everyMinute"`
}
